<?php

declare(strict_types=1);


namespace AmazonPHP\SellingPartner\Model\ProductTypesDefinitions;

use \ArrayAccess;
use \AmazonPHP\SellingPartner\ObjectSerializer;
use \AmazonPHP\SellingPartner\ModelInterface;
use \AmazonPHP\SellingPartner\Exception\AssertionException;

/**
* Selling Partner API for Replenishment
*
* The Selling Partner API for Replenishment (Replenishment API) provides programmatic access to replenishment program metrics and offers. These programs provide recurring delivery of any replenishable item at a frequency chosen by the customer.  The Replenishment API is available worldwide wherever Amazon Subscribe & Save is available or is supported. The API is available to vendors and FBA selling partners.
*
* The version of the OpenAPI document: 2022-11-07
*
* This class was auto-generated by https://openapi-generator.tech
* Do not change it, it will be overwritten with next execution of /bin/generate.sh
 *
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class GetSellingPartnerMetricsRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'GetSellingPartnerMetricsRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static array $openAPITypes = [
        'aggregation_frequency' => '\AmazonPHP\SellingPartner\Model\ProductTypesDefinitions\AggregationFrequency',
        'time_interval' => '\AmazonPHP\SellingPartner\Model\ProductTypesDefinitions\TimeInterval',
        'metrics' => '\AmazonPHP\SellingPartner\Model\ProductTypesDefinitions\Metric[]',
        'time_period_type' => '\AmazonPHP\SellingPartner\Model\ProductTypesDefinitions\TimePeriodType',
        'marketplace_id' => 'string',
        'program_types' => '\AmazonPHP\SellingPartner\Model\ProductTypesDefinitions\ProgramType[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'aggregation_frequency' => null,
        'time_interval' => null,
        'metrics' => null,
        'time_period_type' => null,
        'marketplace_id' => null,
        'program_types' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes() : array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats() : array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static array $attributeMap = [
        'aggregation_frequency' => 'aggregationFrequency',
        'time_interval' => 'timeInterval',
        'metrics' => 'metrics',
        'time_period_type' => 'timePeriodType',
        'marketplace_id' => 'marketplaceId',
        'program_types' => 'programTypes'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static array $setters = [
        'aggregation_frequency' => 'setAggregationFrequency',
        'time_interval' => 'setTimeInterval',
        'metrics' => 'setMetrics',
        'time_period_type' => 'setTimePeriodType',
        'marketplace_id' => 'setMarketplaceId',
        'program_types' => 'setProgramTypes'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static array $getters = [
        'aggregation_frequency' => 'getAggregationFrequency',
        'time_interval' => 'getTimeInterval',
        'metrics' => 'getMetrics',
        'time_period_type' => 'getTimePeriodType',
        'marketplace_id' => 'getMarketplaceId',
        'program_types' => 'getProgramTypes'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap() : array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters() : array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters() : array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName() : string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['aggregation_frequency'] = $data['aggregation_frequency'] ?? null;
        $this->container['time_interval'] = $data['time_interval'] ?? null;
        $this->container['metrics'] = $data['metrics'] ?? null;
        $this->container['time_period_type'] = $data['time_period_type'] ?? null;
        $this->container['marketplace_id'] = $data['marketplace_id'] ?? null;
        $this->container['program_types'] = $data['program_types'] ?? null;
    }

    /**
     * Validate all properties.
     *
     * @throws AssertionException
     */
    public function validate() : void
    {
        if ($this->container['time_interval'] === null) {
            throw new AssertionException("'time_interval' can't be null");
        }

            $this->container['time_interval']->validate();

        if (!is_null($this->container['metrics']) && (count($this->container['metrics']) < 1)) {
            throw new AssertionException("invalid value for 'metrics', number of items must be greater than or equal to 1.");
        }

        if ($this->container['time_period_type'] === null) {
            throw new AssertionException("'time_period_type' can't be null");
        }

        if ($this->container['marketplace_id'] === null) {
            throw new AssertionException("'marketplace_id' can't be null");
        }

        if ($this->container['program_types'] === null) {
            throw new AssertionException("'program_types' can't be null");
        }

        if ((count($this->container['program_types']) < 1)) {
            throw new AssertionException("invalid value for 'program_types', number of items must be greater than or equal to 1.");
        }

    }


    /**
     * Gets aggregation_frequency
     *
     * @return \AmazonPHP\SellingPartner\Model\ProductTypesDefinitions\AggregationFrequency|null
     */
    public function getAggregationFrequency()
    {
        return $this->container['aggregation_frequency'];
    }

    /**
     * Sets aggregation_frequency
     *
     * @param \AmazonPHP\SellingPartner\Model\ProductTypesDefinitions\AggregationFrequency|null $aggregation_frequency aggregation_frequency
     *
     * @return self
     */
    public function setAggregationFrequency($aggregation_frequency) : self
    {
        $this->container['aggregation_frequency'] = $aggregation_frequency;

        return $this;
    }

    /**
     * Gets time_interval
     *
     * @return \AmazonPHP\SellingPartner\Model\ProductTypesDefinitions\TimeInterval
     */
    public function getTimeInterval()
    {
        return $this->container['time_interval'];
    }

    /**
     * Sets time_interval
     *
     * @param \AmazonPHP\SellingPartner\Model\ProductTypesDefinitions\TimeInterval $time_interval time_interval
     *
     * @return self
     */
    public function setTimeInterval($time_interval) : self
    {
        $this->container['time_interval'] = $time_interval;

        return $this;
    }

    /**
     * Gets metrics
     *
     * @return \AmazonPHP\SellingPartner\Model\ProductTypesDefinitions\Metric[]|null
     */
    public function getMetrics()
    {
        return $this->container['metrics'];
    }

    /**
     * Sets metrics
     *
     * @param \AmazonPHP\SellingPartner\Model\ProductTypesDefinitions\Metric[]|null $metrics The list of metrics requested. If no metric value is provided, data for all of the metrics will be returned.
     *
     * @return self
     */
    public function setMetrics($metrics) : self
    {
        $this->container['metrics'] = $metrics;

        return $this;
    }

    /**
     * Gets time_period_type
     *
     * @return \AmazonPHP\SellingPartner\Model\ProductTypesDefinitions\TimePeriodType
     */
    public function getTimePeriodType()
    {
        return $this->container['time_period_type'];
    }

    /**
     * Sets time_period_type
     *
     * @param \AmazonPHP\SellingPartner\Model\ProductTypesDefinitions\TimePeriodType $time_period_type time_period_type
     *
     * @return self
     */
    public function setTimePeriodType($time_period_type) : self
    {
        $this->container['time_period_type'] = $time_period_type;

        return $this;
    }

    /**
     * Gets marketplace_id
     *
     * @return string
     */
    public function getMarketplaceId()
    {
        return $this->container['marketplace_id'];
    }

    /**
     * Sets marketplace_id
     *
     * @param string $marketplace_id The marketplace identifier. The supported marketplaces for both sellers and vendors are US, CA, ES, UK, FR, IT, IN, DE and JP. The supported marketplaces for vendors only are BR, AU, MX, AE and NL. Refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids) to find the identifier for the marketplace.
     *
     * @return self
     */
    public function setMarketplaceId($marketplace_id) : self
    {
        $this->container['marketplace_id'] = $marketplace_id;

        return $this;
    }

    /**
     * Gets program_types
     *
     * @return \AmazonPHP\SellingPartner\Model\ProductTypesDefinitions\ProgramType[]
     */
    public function getProgramTypes()
    {
        return $this->container['program_types'];
    }

    /**
     * Sets program_types
     *
     * @param \AmazonPHP\SellingPartner\Model\ProductTypesDefinitions\ProgramType[] $program_types A list of replenishment program types.
     *
     * @return self
     */
    public function setProgramTypes($program_types) : self
    {
        $this->container['program_types'] = $program_types;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @return boolean
     */
    public function offsetExists($offset) : bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @return void
     */
    public function offsetSet($offset, $value) : void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @return void
     */
    public function offsetUnset($offset) : void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize() : string
    {
       return \json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString() : string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue() : string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

