<?php

declare(strict_types=1);


namespace AmazonPHP\SellingPartner\Model\ProductTypesDefinitions;

use \ArrayAccess;
use \AmazonPHP\SellingPartner\ObjectSerializer;
use \AmazonPHP\SellingPartner\ModelInterface;
use \AmazonPHP\SellingPartner\Exception\AssertionException;

/**
* Selling Partner API for Replenishment
*
* The Selling Partner API for Replenishment (Replenishment API) provides programmatic access to replenishment program metrics and offers. These programs provide recurring delivery of any replenishable item at a frequency chosen by the customer.  The Replenishment API is available worldwide wherever Amazon Subscribe & Save is available or is supported. The API is available to vendors and FBA selling partners.
*
* The version of the OpenAPI document: 2022-11-07
*
* This class was auto-generated by https://openapi-generator.tech
* Do not change it, it will be overwritten with next execution of /bin/generate.sh
 *
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class Promotion implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'Promotion';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static array $openAPITypes = [
        'selling_partner_funded_base_discount' => '\AmazonPHP\SellingPartner\Model\ProductTypesDefinitions\DiscountFunding',
        'selling_partner_funded_tiered_discount' => '\AmazonPHP\SellingPartner\Model\ProductTypesDefinitions\DiscountFunding',
        'amazon_funded_base_discount' => '\AmazonPHP\SellingPartner\Model\ProductTypesDefinitions\DiscountFunding',
        'amazon_funded_tiered_discount' => '\AmazonPHP\SellingPartner\Model\ProductTypesDefinitions\DiscountFunding'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'selling_partner_funded_base_discount' => null,
        'selling_partner_funded_tiered_discount' => null,
        'amazon_funded_base_discount' => null,
        'amazon_funded_tiered_discount' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes() : array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats() : array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static array $attributeMap = [
        'selling_partner_funded_base_discount' => 'sellingPartnerFundedBaseDiscount',
        'selling_partner_funded_tiered_discount' => 'sellingPartnerFundedTieredDiscount',
        'amazon_funded_base_discount' => 'amazonFundedBaseDiscount',
        'amazon_funded_tiered_discount' => 'amazonFundedTieredDiscount'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static array $setters = [
        'selling_partner_funded_base_discount' => 'setSellingPartnerFundedBaseDiscount',
        'selling_partner_funded_tiered_discount' => 'setSellingPartnerFundedTieredDiscount',
        'amazon_funded_base_discount' => 'setAmazonFundedBaseDiscount',
        'amazon_funded_tiered_discount' => 'setAmazonFundedTieredDiscount'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static array $getters = [
        'selling_partner_funded_base_discount' => 'getSellingPartnerFundedBaseDiscount',
        'selling_partner_funded_tiered_discount' => 'getSellingPartnerFundedTieredDiscount',
        'amazon_funded_base_discount' => 'getAmazonFundedBaseDiscount',
        'amazon_funded_tiered_discount' => 'getAmazonFundedTieredDiscount'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap() : array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters() : array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters() : array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName() : string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['selling_partner_funded_base_discount'] = $data['selling_partner_funded_base_discount'] ?? null;
        $this->container['selling_partner_funded_tiered_discount'] = $data['selling_partner_funded_tiered_discount'] ?? null;
        $this->container['amazon_funded_base_discount'] = $data['amazon_funded_base_discount'] ?? null;
        $this->container['amazon_funded_tiered_discount'] = $data['amazon_funded_tiered_discount'] ?? null;
    }

    /**
     * Validate all properties.
     *
     * @throws AssertionException
     */
    public function validate() : void
    {
            if ($this->container['selling_partner_funded_base_discount'] !== null) {
            $this->container['selling_partner_funded_base_discount']->validate();
            }

            if ($this->container['selling_partner_funded_tiered_discount'] !== null) {
            $this->container['selling_partner_funded_tiered_discount']->validate();
            }

            if ($this->container['amazon_funded_base_discount'] !== null) {
            $this->container['amazon_funded_base_discount']->validate();
            }

            if ($this->container['amazon_funded_tiered_discount'] !== null) {
            $this->container['amazon_funded_tiered_discount']->validate();
            }

    }


    /**
     * Gets selling_partner_funded_base_discount
     *
     * @return \AmazonPHP\SellingPartner\Model\ProductTypesDefinitions\DiscountFunding|null
     */
    public function getSellingPartnerFundedBaseDiscount()
    {
        return $this->container['selling_partner_funded_base_discount'];
    }

    /**
     * Sets selling_partner_funded_base_discount
     *
     * @param \AmazonPHP\SellingPartner\Model\ProductTypesDefinitions\DiscountFunding|null $selling_partner_funded_base_discount selling_partner_funded_base_discount
     *
     * @return self
     */
    public function setSellingPartnerFundedBaseDiscount($selling_partner_funded_base_discount) : self
    {
        $this->container['selling_partner_funded_base_discount'] = $selling_partner_funded_base_discount;

        return $this;
    }

    /**
     * Gets selling_partner_funded_tiered_discount
     *
     * @return \AmazonPHP\SellingPartner\Model\ProductTypesDefinitions\DiscountFunding|null
     */
    public function getSellingPartnerFundedTieredDiscount()
    {
        return $this->container['selling_partner_funded_tiered_discount'];
    }

    /**
     * Sets selling_partner_funded_tiered_discount
     *
     * @param \AmazonPHP\SellingPartner\Model\ProductTypesDefinitions\DiscountFunding|null $selling_partner_funded_tiered_discount selling_partner_funded_tiered_discount
     *
     * @return self
     */
    public function setSellingPartnerFundedTieredDiscount($selling_partner_funded_tiered_discount) : self
    {
        $this->container['selling_partner_funded_tiered_discount'] = $selling_partner_funded_tiered_discount;

        return $this;
    }

    /**
     * Gets amazon_funded_base_discount
     *
     * @return \AmazonPHP\SellingPartner\Model\ProductTypesDefinitions\DiscountFunding|null
     */
    public function getAmazonFundedBaseDiscount()
    {
        return $this->container['amazon_funded_base_discount'];
    }

    /**
     * Sets amazon_funded_base_discount
     *
     * @param \AmazonPHP\SellingPartner\Model\ProductTypesDefinitions\DiscountFunding|null $amazon_funded_base_discount amazon_funded_base_discount
     *
     * @return self
     */
    public function setAmazonFundedBaseDiscount($amazon_funded_base_discount) : self
    {
        $this->container['amazon_funded_base_discount'] = $amazon_funded_base_discount;

        return $this;
    }

    /**
     * Gets amazon_funded_tiered_discount
     *
     * @return \AmazonPHP\SellingPartner\Model\ProductTypesDefinitions\DiscountFunding|null
     */
    public function getAmazonFundedTieredDiscount()
    {
        return $this->container['amazon_funded_tiered_discount'];
    }

    /**
     * Sets amazon_funded_tiered_discount
     *
     * @param \AmazonPHP\SellingPartner\Model\ProductTypesDefinitions\DiscountFunding|null $amazon_funded_tiered_discount amazon_funded_tiered_discount
     *
     * @return self
     */
    public function setAmazonFundedTieredDiscount($amazon_funded_tiered_discount) : self
    {
        $this->container['amazon_funded_tiered_discount'] = $amazon_funded_tiered_discount;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @return boolean
     */
    public function offsetExists($offset) : bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @return void
     */
    public function offsetSet($offset, $value) : void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @return void
     */
    public function offsetUnset($offset) : void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize() : string
    {
       return \json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString() : string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue() : string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

