generatorName: php
templateDir: sp-api/resources/php-amazon-selling-partner-api
additionalProperties:
  invokerPackage: AmazonPHP\SellingPartner
  srcBasePath: src/AmazonPHP/SellingPartner
  modelPackage: Model\AmazonWarehousingAndDistribution
  packageName: AmazonWarehousingAndDistribution
files:
  api.mustache:
    templateType: API
    destinationFilename: /AmazonWarehousingAndDistributionSDK.php
  api_interface.mustache:
    templateType: API
    destinationFilename: /AmazonWarehousingAndDistributionSDKInterface.php