generatorName: php
templateDir: sp-api/resources/php-amazon-selling-partner-api
additionalProperties:
  invokerPackage: AmazonPHP\SellingPartner
  srcBasePath: src/AmazonPHP/SellingPartner
  modelPackage: Model\Replenishment
  packageName: Replenishment
files:
  api.mustache:
    templateType: API
    destinationFilename: /ReplenishmentSDK.php
  api_interface.mustache:
    templateType: API
    destinationFilename: /ReplenishmentSDKInterface.php