generatorName: php
templateDir: sp-api/resources/php-amazon-selling-partner-api
additionalProperties:
  invokerPackage: AmazonPHP\SellingPartner
  srcBasePath: src/AmazonPHP/SellingPartner
  modelPackage: Model\DataKiosk
  packageName: DataKiosk
files:
  api.mustache:
    templateType: API
    destinationFilename: /DataKioskSDK.php
  api_interface.mustache:
    templateType: API
    destinationFilename: /DataKioskSDKInterface.php